version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules:/etc/prometheus/alert.rules
    links:
      - node_exporter
      - alertmanager
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always


  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command:
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  promtail-loki:
    image: grafana/promtail:master
    volumes:
      - ./config/prom-conf.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      driver: "json-file"
      options: 
        tag: "{{.Name}}"
    command:
      - -config.file=/etc/promtail/config.yaml
    ports:
      - 3100:3100
  
volumes:
  prometheus_data: